// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package dglite

import (
	"database/sql"
)

type Block struct {
	ID   int64
	Data []byte
}

type File struct {
	ID       int64
	Type     sql.NullString
	Name     sql.NullString
	Readkey  sql.NullString
	Writekey sql.NullString
	Size     sql.NullInt64
}
