// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package dglite

import (
	"context"
)

const getDb = `-- name: GetDb :one
select id, type, name, readkey, writekey, size from file where id=?
`

func (q *Queries) GetDb(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getDb, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Readkey,
		&i.Writekey,
		&i.Size,
	)
	return i, err
}
