// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package mangrove_sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MgDb struct {
	Db   int32
	Name string
}

type MgDbfile struct {
	Db    int64
	Count int16
	Path  string
	Fid   pgtype.Int8
	Size  pgtype.Int8
	Mime  string
	Mt    pgtype.Timestamp
}

type MgDbfileh struct {
	Db    int64
	Count int16
	Path  string
	Fid   int64
	Size  pgtype.Int8
	Mime  string
	Mt    pgtype.Timestamp
}

type MgDevice struct {
	Device   string
	Webauthn string
}

type MgDeviceOrg struct {
	Device string
	Org    string
	Ucan   string
}

type MgNameprefix struct {
	Name  string
	Count int64
}

type MgOrg struct {
	Org    string
	Name   pgtype.Text
	IsUser bool
}

type MgOrgDb struct {
	Org string
	Db  int64
}

type MgOrgMember struct {
	Org    interface{}
	Member string
	Ucan   pgtype.Text
}

type MgSegment struct {
	Fid   int32
	Start int64
	Data  []byte
	Ts    interface{}
	Mt    pgtype.Timestamp
}
