// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package mangrove_sql

import (
	"database/sql"
)

type Credential struct {
	Did      string
	Name     string
	Webauthn sql.NullString
}

type Db struct {
	Db   int32
	Name sql.NullString
}

type Dbfile struct {
	Db    int64
	Count int16
	Path  string
	Fid   sql.NullInt64
	Size  sql.NullInt64
	Mime  sql.NullString
}

type Org struct {
	Did  string
	Name sql.NullString
}

type Segment struct {
	Fid   int32
	Start int64
	Data  []byte
	Ts    interface{}
}

type UserDb struct {
	Uid string
	Db  int64
}
